[profile.default]
src = ""
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = ["@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts", "@openzeppelin=lib/openzeppelin-contracts/contracts",
"@openzeppelin-upgrades=lib/openzeppelin-foundry-upgrades/src"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

